DROP TABLE "LOGIN_LOG";
DROP TABLE "BOARD_POST";
DROP TABLE "WISHLIST";
DROP TABLE "GAMEREVIEW";
DROP TABLE "COMMENT_POST";
DROP TABLE "GAME_BUY";
DROP TABLE "GAME";
DROP TABLE "COMMENTS";
DROP TABLE "BOARD_FILE";
DROP TABLE "BOARD";
DROP TABLE "MEMBER";

CREATE TABLE "LOGIN_LOG" (
	"LOG_TIME"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"LOG_IP"	VARCHAR2(15)		NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"LOG_TYPE"	CHAR(1)	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "LOGIN_LOG"."LOG_TIME" IS '로그아웃한 시간';

COMMENT ON COLUMN "LOGIN_LOG"."LOG_IP" IS '로그인한 단말의 IP4(000.000.000.000)';

COMMENT ON COLUMN "LOGIN_LOG"."MEM_ID" IS '멤버아이디 영문자,숫자,_';

COMMENT ON COLUMN "LOGIN_LOG"."LOG_TYPE" IS '로그인(1), 로그아웃(2)';



CREATE TABLE "BOARD" (
	"BOARD_ID"	NUMBER		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(30)		NOT NULL,
	"BOARD_DETAIL"	VARCHAR2(225)		NOT NULL,
	"BOARD_WRITER"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"BOARD_WRITER_MODIFY"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NULL,
	"PLAY_TIME"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NULL,
	"COMMENT_COUNT"	NUMBER		NULL,
	"REC_COUNT"	NUMBER		NULL,
	"NOTREC_COUNT"	NUMBER		NULL,
	"EXPRESSION_COUNT"	NUMBER		NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_ID" IS '게시글 번호';

COMMENT ON COLUMN "BOARD"."MEM_ID" IS '멤버아이디 영문자,숫자,_';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_DETAIL" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."BOARD_WRITER" IS '게시글 작성 시간';

COMMENT ON COLUMN "BOARD"."BOARD_WRITER_MODIFY" IS '게시글 수정 시간';

COMMENT ON COLUMN "BOARD"."PLAY_TIME" IS '플레이한 시간';

COMMENT ON COLUMN "BOARD"."COMMENT_COUNT" IS '댓글수 - 댓글달때마다 증가';

COMMENT ON COLUMN "BOARD"."REC_COUNT" IS '추천수 - 클릭시 증가';

COMMENT ON COLUMN "BOARD"."NOTREC_COUNT" IS '비추천 - 클릭시 증가';

COMMENT ON COLUMN "BOARD"."EXPRESSION_COUNT" IS '표정수 - 표정 버튼을 누르면 증가';



CREATE TABLE "BOARD_POST" (
	"BOARD_ID"	NUMBER		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"POST_WRITER"	VARCHAR2(500)		NULL
);

COMMENT ON COLUMN "BOARD_POST"."BOARD_ID" IS '게시글 번호';

COMMENT ON COLUMN "BOARD_POST"."MEM_ID" IS '멤버아이디 영문자,숫자,_';

COMMENT ON COLUMN "BOARD_POST"."POST_WRITER" IS '게시글 신고 내용';



CREATE TABLE "BOARD_FILE" (
	"BOARD_FILE_ID"	NUMBER(5)		NOT NULL,
	"BOARD_ID"	NUMBER		NOT NULL,
	"BOARD_FILE_PATH_NAME"	VARCHAR2(1000)		NOT NULL,
	"ORIGINAL_BOARD_FILE"	VARCHAR2(300)		NOT NULL
);

COMMENT ON COLUMN "BOARD_FILE"."BOARD_FILE_ID" IS '파일 번호';

COMMENT ON COLUMN "BOARD_FILE"."BOARD_ID" IS '게시글 번호';

COMMENT ON COLUMN "BOARD_FILE"."BOARD_FILE_PATH_NAME" IS '파일경로명';

COMMENT ON COLUMN "BOARD_FILE"."ORIGINAL_BOARD_FILE" IS '클라이언트로 전송된 원본파일';



CREATE TABLE "MEMBER" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_PWD"	VARCHAR2(30)		NOT NULL,
	"MEM_EMAIL"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEM_ID" IS '멤버아이디 영문자,숫자,_';

COMMENT ON COLUMN "MEMBER"."MEM_PWD" IS '멤버비밀번호 영문자,숫자,특수기호 합해서 8자리 이상';

COMMENT ON COLUMN "MEMBER"."MEM_EMAIL" IS '멤버이메일';



CREATE TABLE "COMMENTS" (
	"COMMENT_ID"	NUMBER		NOT NULL,
	"BOARD_ID2"	NUMBER		NOT NULL,
	"COMMENT_DETAIL"	VARCHAR2(140)		NULL,
	"COMMENT_TIME"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "COMMENTS"."COMMENT_ID" IS '댓글 번호';

COMMENT ON COLUMN "COMMENTS"."BOARD_ID2" IS '게시글 번호';

COMMENT ON COLUMN "COMMENTS"."COMMENT_DETAIL" IS '댓글 내용 140자 이내';

COMMENT ON COLUMN "COMMENTS"."COMMENT_TIME" IS '댓글 작성된 시간';

COMMENT ON COLUMN "COMMENTS"."MEM_ID" IS '멤버아이디 영문자,숫자,_';



CREATE TABLE "WISHLIST" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "WISHLIST"."MEM_ID" IS '멤버아이디 영문자,숫자,_';



CREATE TABLE "GAME" (
	"GAME_ID"	NUMBER		NOT NULL,
	"GAME_PRICE"	NUMBER		NOT NULL,
	"GAME_TITLE"	VARCHAR2(255)		NOT NULL,
	"GAME_EXP"	VARCHAR2(255)		NOT NULL,
	"GAME_TAG"	VARCHAR2(20)		NULL,
	"GAME_RD"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"GAME_GRADE"	VARCHAR(255)		NULL,
	"GAME_REVIEW"	VARCHAR2(300)		NOT NULL,
	"GAME_WISH"	CHAR(1)	DEFAULT 1	NULL
);

COMMENT ON COLUMN "GAME"."GAME_ID" IS '게임 고유의 식별번호';

COMMENT ON COLUMN "GAME"."GAME_PRICE" IS '게임 가격';

COMMENT ON COLUMN "GAME"."GAME_TITLE" IS '게임 제목';

COMMENT ON COLUMN "GAME"."GAME_EXP" IS '게임 설명';

COMMENT ON COLUMN "GAME"."GAME_TAG" IS '게임 장르 태그';

COMMENT ON COLUMN "GAME"."GAME_RD" IS '게임 출시일(YYYYMMDD)';

COMMENT ON COLUMN "GAME"."GAME_GRADE" IS '게임 평가';

COMMENT ON COLUMN "GAME"."GAME_REVIEW" IS '게임 리뷰';

COMMENT ON COLUMN "GAME"."GAME_WISH" IS '찜하지 않음(1), 찜(2)';


CREATE TABLE "GAMEREVIEW" (
	"REVIEW_ID"	NUMBER		NOT NULL,
	"GAME_ID"	NUMBER		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"OFFER_COUNT"	NUMBER		NOT NULL,
	"NOTREC_COUNT"	NUMBER		NOT NULL,
	"REVIEW_DETAIL"	VARCHAR2(225)		NULL
);

COMMENT ON COLUMN "GAMEREVIEW"."REVIEW_ID" IS '게임 리뷰글 고유의 번호';

COMMENT ON COLUMN "GAMEREVIEW"."GAME_ID" IS '게임 고유의 식별번호';

COMMENT ON COLUMN "GAMEREVIEW"."MEM_ID" IS '멤버아이디 영문자,숫자,_';

COMMENT ON COLUMN "GAMEREVIEW"."OFFER_COUNT" IS '추천';

COMMENT ON COLUMN "GAMEREVIEW"."NOTREC_COUNT" IS '비추천';

COMMENT ON COLUMN "GAMEREVIEW"."REVIEW_DETAIL" IS '리뷰글 내용';



CREATE TABLE "GAME_BUY" (
	"GAME_ID"	NUMBER		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"GAME_TIME"	TIMESTAMP		NOT NULL,
	"GAME_BUY_ID"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "GAME_BUY"."GAME_ID" IS '게임 고유의 식별번호';

COMMENT ON COLUMN "GAME_BUY"."MEM_ID" IS '멤버아이디 영문자,숫자,_';

COMMENT ON COLUMN "GAME_BUY"."GAME_TIME" IS '게임을 구매한 시간(YYYY-MM-DD hh:mm)';

COMMENT ON COLUMN "GAME_BUY"."GAME_BUY_ID" IS '각 구매에 대한 고유의 아이디';



CREATE TABLE "COMMENT_POST" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"COMMENT_ID"	NUMBER		NOT NULL,
	"BOARD_ID2"	NUMBER		NOT NULL,
	"COMMENT_WRITER"	VARCHAR2(225)		NULL
);

COMMENT ON COLUMN "COMMENT_POST"."MEM_ID" IS '멤버아이디 영문자,숫자,_';

COMMENT ON COLUMN "COMMENT_POST"."COMMENT_ID" IS '댓글 번호';

COMMENT ON COLUMN "COMMENT_POST"."BOARD_ID2" IS '게시글 번호';

COMMENT ON COLUMN "COMMENT_POST"."COMMENT_WRITER" IS '댓글 신고 내용';

ALTER TABLE "LOGIN_LOG" ADD CONSTRAINT "PK_LOGIN_LOG" PRIMARY KEY (
	"LOG_TIME",
	"LOG_IP",
	"MEM_ID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_ID"
);

ALTER TABLE "BOARD_POST" ADD CONSTRAINT "PK_BOARD_POST" PRIMARY KEY (
	"BOARD_ID",
	"MEM_ID"
);

ALTER TABLE "BOARD_FILE" ADD CONSTRAINT "PK_BOARD_FILE" PRIMARY KEY (
	"BOARD_FILE_ID",
	"BOARD_ID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "COMMENTS" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_ID",
	"BOARD_ID2"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "PK_WISHLIST" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "GAME" ADD CONSTRAINT "PK_GAME" PRIMARY KEY (
	"GAME_ID"
);

ALTER TABLE "GAMEREVIEW" ADD CONSTRAINT "PK_GAMEREVIEW" PRIMARY KEY (
	"REVIEW_ID",
	"GAME_ID",
	"MEM_ID"
);

ALTER TABLE "GAME_BUY" ADD CONSTRAINT "PK_GAME_BUY" PRIMARY KEY (
	"GAME_ID",
	"MEM_ID"
);

ALTER TABLE "COMMENT_POST" ADD CONSTRAINT "PK_COMMENT_POST" PRIMARY KEY (
	"MEM_ID",
	"COMMENT_ID",
	"BOARD_ID2"
);

ALTER TABLE "LOGIN_LOG" ADD CONSTRAINT "FK_MEMBER_TO_LOGIN_LOG_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "BOARD_POST" ADD CONSTRAINT "FK_BOARD_TO_BOARD_POST_1" FOREIGN KEY (
	"BOARD_ID"
)
REFERENCES "BOARD" (
	"BOARD_ID"
);

ALTER TABLE "BOARD_POST" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_POST_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "BOARD_FILE" ADD CONSTRAINT "FK_BOARD_TO_BOARD_FILE_1" FOREIGN KEY (
	"BOARD_ID"
)
REFERENCES "BOARD" (
	"BOARD_ID"
);

ALTER TABLE "COMMENTS" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_ID2"
)
REFERENCES "BOARD" (
	"BOARD_ID"
);

ALTER TABLE "COMMENTS" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_MEMBER_TO_WISHLIST_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "GAMEREVIEW" ADD CONSTRAINT "FK_GAME_TO_GAMEREVIEW_1" FOREIGN KEY (
	"GAME_ID"
)
REFERENCES "GAME" (
	"GAME_ID"
);

ALTER TABLE "GAMEREVIEW" ADD CONSTRAINT "FK_MEMBER_TO_GAMEREVIEW_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "GAME_BUY" ADD CONSTRAINT "FK_GAME_TO_GAME_BUY_1" FOREIGN KEY (
	"GAME_ID"
)
REFERENCES "GAME" (
	"GAME_ID"
);

ALTER TABLE "GAME_BUY" ADD CONSTRAINT "FK_MEMBER_TO_GAME_BUY_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "COMMENT_POST" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_POST_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "COMMENT_POST" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_POST_1" FOREIGN KEY (
	"COMMENT_ID"
    ,"BOARD_ID2"
)
REFERENCES "COMMENTS" (
	"COMMENT_ID"
    ,"BOARD_ID2"
);



